# PostgreSQL. Versions 9.1 and up are supported.
# gem 'pg'

default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: seen_development
  user: <%= ENV['SEEN_DEVELOPMENT_DATABASE_USER'] %>
  password: <%= ENV['SEEN_DEVELOPMENT_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: seen_test

production:
  <<: *default
  database: seen_production
  username: <%= ENV['SEEN_PRODUCTION_DATABASE_USER'] %>
  password: <%= ENV['SEEN_PRODUCTION_DATABASE_PASSWORD'] %>
